### ISSUE TITLE
Changes from UX meeting before release Onboarding, Search

### ISSUE THREAD

**Issue by OndrejMalek** [cesko-digital/movapp-android#12]
**onboarding** 
- can back off the app

**Search**
- going between favourites and dict remember searched word and when switching filter by already typed word (it does not now)
- when search word is erased show all items favourites/phrases
- favourites star not filled color but only stroke when no selected

**Comment by OndrejMalek** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Changes from UX meeting before release Onboarding, Search](https://trello.com/c/pFNmsigj/177-changes-from-ux-meeting-before-release-onboarding-search)

**Comment by vchlum** [comment]
done
