### ISSUE TITLE
Can not go to Favorites after return from settings

### ISSUE THREAD

**Issue by OndrejMalek** [cesko-digital/movapp-android#13]
tab click not working

**Steps to reproduce:**
1. open app
2. in dict click phrase section
3. type 'ro' into search field
4. click bottom bar 'favorites'
5. click bottom bar 'settings' 
6. click bottom bar 'dict'
result: U are in dict-dict, when click favorites tab nothing happens
expected: U are in dict-favorites, tab click are working

**Comment by OndrejMalek** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [df](https://trello.com/c/4TxDpGoI/179-df)

**Comment by vchlum** [comment]
done
