### ISSUE TITLE
Memory game for kids (Pexeso)

### ISSUE THREAD

**Issue by OndrejMalek** [cesko-digital/movapp-android#19]
Create screen with Pexeso as on web https://www.movapp.cz/kids/memory-game , https://github.com/cesko-digital/movapp/pull/109

1. Migrate data for pexeso (images and translations) from web https://github.com/cesko-digital/movapp to https://github.com/cesko-digital/movapp-data/
2. Kids navigation screen - (so far not specified with UX team it might change) Top Kids screen accessible thru bottom app bar which should contain navigation to current Kids screen / Pexeso / Fairy tales (in future)
3. Pexeso screen - so far can be with fixed width/height

**Comment by vchlum** [comment]
done
