### ISSUE TITLE
Small fixes to slovak l10n

### ISSUE THREAD

**Issue by met** [cesko-digital/movapp-android#24]
We have several smoll fixes to Sloval localization.

 https://cesko-digital.slack.com/archives/C036GLKL7ME/p1662442438911749?thread_ts=1662311311.467089&cid=C036GLKL7ME

**Comment by met** [comment]
Here is the fix for iOS (Android should be similar) https://github.com/cesko-digital/movapp-apple/commit/fa324ba9970046e9fb3ea33c8ec2c32cc4722713#diff-34decd07efb1692be2ae7a591ebfbcd13825f69cd63b94ac12e603bf3de7ca66

**Comment by vchlum** [comment]
Done
