### ISSUE TITLE
Obrazovka Slovníček_UJ-SJ mutace_sekce Čísla_místo 70 je ve SJ číslo 17

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#26]
**Describe the bug**
[Obrazovka Slovníček_UJ-SJ mutace_sekce Čísla_místo 70 je ve SJ číslo 17]

**To Reproduce**
[Slovníček - Čísla - 70]

**Expected behavior**
[ve SJ je u číslovky 70 napsáno "sedemdesiat", stejně tak se po kliknutí na tlačítko zvuku přehraje slovo "sedemdesiat".]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
![MOVAPP_bug_01](https://user-images.githubusercontent.com/117156625/208175646-df28ea92-d300-4e95-b7e3-dfe280c8f1cf.jpg)

**Comment by met** [comment]
Opraveno v datech https://github.com/cesko-digital/movapp-data/commit/c4dd35d83778c46026ba11fb5f2d89e2f8e4c1a1

@vchlum Obsahové bugy si nejlíp asi assignu já. Zajístím opravu a označím, když budou opraveny v Movapp data. 
Navrhni si další postup. Já můžu třeba přidat label "fixed-in-data" jako signál, když je to opraveno v datech.
Až naimportuješ nová data a vydáš novou verzi aplikace, měla by Mariana dostat nějaký signál, že má zkontrolovat, jestli je to opravdu opraveno. Možná taky nějakým štítkem.

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.6.1
