### ISSUE TITLE
Obrazovka Slovníček_UJ-SJ mutace_sekce Vianoce_zvon/zvonček_čteno i s lomítkem

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#27]
**Describe the bug**
[Obrazovka Slovníček_UJ-SJ mutace_sekce Vianoce_zvon/zvonček_přehraje se "zvon lomka zvonček"]

**To Reproduce**
[Slovníček - Vianoce - zvon/zvonček]

**Expected behavior**
[výraz zvon/zvonček se po kliknutí na tlačítko zvuku přehraje jako "zvon, zvonček"]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.6.1
