### ISSUE TITLE
Obrazovka Slovníček_UJ-SJ mutace_sekce Práca - chybí obsah 

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#28]
**Describe the bug**
[Obrazovka Slovníček_UJ-SJ mutace_sekce Práca - chybí obsah]

**To Reproduce**
[Slovníček - Práca]

**Expected behavior**
[Po kliknutí na sekci Práca se objeví obsah sekce.]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.6.1
