### ISSUE TITLE
Obrazovka Slovníček_UJ-SJ mutace_sekce U lekára_slovo paža je 2x

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#29]
**Describe the bug**
[Obrazovka Slovníček_UJ-SJ mutace_sekce U lekára_slovo paža (i v UJ překladu) je 2x]

**To Reproduce**
[Slovníček - U lekára - paža]

**Expected behavior**
[Slovo paža se zobrazuje jednou.]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
![MOVAPP_bug_02](https://user-images.githubusercontent.com/117156625/208180450-33685a3d-8bad-4399-bfbe-6513b175819a.jpg)

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.6.1
