### ISSUE TITLE
Obrazovka Slovníček_UJ-SJ mutace_sekce Rozprávky_trojhlavý drak se otevírá se zpožděním

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#30]
**Describe the bug**
[Obrazovka Slovníček_UJ-SJ mutace_sekce Rozprávky_trojhlavý drak se otevírá se zpožděním]

**To Reproduce**
[Slovníček - Pre deti - zpět do Slovníčku - Rozprávky]

**Expected behavior**
[v sekci Rozprávky se otevřou všechny položky ve stejný čas]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.6.1
