### ISSUE TITLE
Obrazovka Abeceda_slovenská abeceda_Dž_chybí jedno tlačítko pro přehrání zvuku

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#32]
**Describe the bug**
[Obrazovka Abeceda_slovenská abeceda_Dž_chybí jedno tlačítko pro přehrání zvuku - pod jedním tlačítkem zvuku jsou dva výrazy  - džem, džús]

**To Reproduce**
[Abeceda - slovenská abeceda - Dž]

**Expected behavior**
[U písmene Dž jsou tři tlačítka pro přehrání zvuku - 1. pro džem, 2. pro džús, 3. pro džínsy]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
![MOVAPP_bug_03](https://user-images.githubusercontent.com/117156625/208186108-590c3a13-188f-4b56-a009-2ce97fef52c9.jpg)

**Comment by met** [comment]
Opraveno v movapp-data, v příští verzi bude vyřešeno.

**Comment by Lebedito** [comment]
Martine děkuji a jaký je prosím postup pro evidenci bugů zde v GitHub? Až se ta oprava v příští verzi promítne a já to zkontroluji jak to mám tady uzavřít?

**Comment by met** [comment]
@Lebedito Počkej na další verzi (ať už beta verzi nebo veřejnou verzi) a zkontroluj v ní ty issues, u kterých jsem nastavil to "fixed-in-data" (barevný label, který jsem přidal i k tomuhle issue), jestli jsou opravdu vyřešené. Když budou, tak je uzavři.

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.6.1
