### ISSUE TITLE
Obrazovka Abeceda_česká abeceda_I_výslovnost slova iglů se přehrává jako "igeleu" 

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#33]
**Describe the bug**
[Obrazovka Abeceda_česká abeceda_I_výslovnost slova iglů se přehrává jako "igeleu"]

**To Reproduce**
[Abeceda - česká abeceda - I]

**Expected behavior**
[slovo iglů u písmena I se po kliknutí na tlačítko zvuku přehraje jako "iglů"]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.7.0
