### ISSUE TITLE
Obrazovka Abeceda_česká abeceda_Q_výslovnost slova Quido se přehrává jako "kvujdo"

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#34]
**Describe the bug**
[Obrazovka Abeceda_česká abeceda_Q_výslovnost slova Quido se přehrává jako "kvujdo"]

**To Reproduce**
[Abeceda - česká abeceda - Q]

**Expected behavior**
[slovo Quido u písmena Q se po kliknutí na tlačítko zvuku přehraje jako "Kvído"]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.7.0
