### ISSUE TITLE
Obrazovka Pro děti_karta Slovníček_UJ-ČJ mutace_puzzle v ČJ se přehrává jako "pazl"

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#35]
**Describe the bug**
[Obrazovka Pro děti_karta Slovníček_UJ-ČJ mutace_puzzle se přehrává jako "pazl"]

**To Reproduce**
[Pro děti - Slovníček - puzzle]

**Expected behavior**
[slovo puzzle se po kliknutí na tlačítko zvuku přehraje jako "pucle"]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.7.0
