### ISSUE TITLE
Obrazovka Slovníček_UJ - ČJ mutace_sekce Vánoce_zvon/zvoneček_čteno i s lomítkem

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#36]
**Describe the bug**
[Obrazovka Slovníček_UJ-ČJ mutace_sekce Vánoce_zvon/zvoneček_přehraje se "zvon lomítko zvoneček"]

**To Reproduce**
[Slovníček - Vánoce - zvon/zvoneček]

**Expected behavior**
[výraz zvon/zvoneček se po kliknutí na tlačítko zvuku přehraje jako "zvon, zvoneček"]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.7.0
