### ISSUE TITLE
Obrazovka Slovníček_UJ - ČJ mutace_sekce Zima_Jezdíte v zime na hory?_zimě čteno bez ě

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#37]
**Describe the bug**
[Obrazovka Slovníček_UJ-ČJ mutace_sekce Zima_Jezdíte v zime na hory? Slovo "zimě" čteno bez ě (jako "zime")]

**To Reproduce**
[Slovníček - Zima - Jezdíte v zimě na hory?]

**Expected behavior**
[Jezdíte v zimě na hory? se po kliknutí na tlačítko zvuku přehraje jako "Jezdíte v **zimě** na hory?"]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.6.1
