### ISSUE TITLE
Obrazovka Slovníček_UJ - ČJ mutace_sekce Na úřadě_e-mailová adresa se přehraje jako "e-mejlová adresa"

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#38]
**Describe the bug**
[Obrazovka Slovníček_UJ - ČJ mutace_sekce Na úřadě_e-mailová adresa se přehraje jako "e-mejlová adresa"]

**To Reproduce**
[Slovníček - Na úřadě - e-mailová adresa]

**Expected behavior**
[výraz e-mailová adresa se po kliknutí na tlačítko zvuku přehraje jako "ímejlová adresa"]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.7.0
