### ISSUE TITLE
Obrazovka Slovníček_UJ - ČJ mutace_sekce Práce_IS/IT čteno s lomítkem a IS je čteno foneticky 

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#39]
**Describe the bug**
[Obrazovka Slovníček_UJ - ČJ mutace_sekce Práce_IS/IT čteno s lomítkem a IS je čteno foneticky. 1. položka je IS/IT: Konzultace, analýzy a projektové řízení, 2. položka je: IS/IT: Správa systémů a HW - HW je čteno jako "hádvojitévé", 3. položka: IS/IT: Vývoj aplikací a systémů]

**To Reproduce**
[Slovníček - Práce - IS/IT: Konzultace, analýzy a projektové řízení, IS/IT: Správa systémů a HW, IS/IT: Vývoj aplikací a systémů]

**Expected behavior**
[IS/IT je čteno bez lomítka, IS je čteno jako "í es", HW je čteno jako "há vé"?]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.7.0
