### ISSUE TITLE
Obrazovka Slovníček_UJ - ČJ mutace_sekce Práce_5 týdnů dovolené čteno jako "pěti týdnů dovolené"

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#40]
**Describe the bug**
[Obrazovka Slovníček_UJ - ČJ mutace_sekce Práce_5 týdnů dovolené čteno jako "**pěti** týdnů dovolené"]

**To Reproduce**
[Slovníček - Práce - 5 týdnů dovolené]

**Expected behavior**
[výraz 5 týdnů dovolené se po kliknutí na tlačítko zvuku přehraje jako "pět týdnů dovolené"]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.7.0
