### ISSUE TITLE
Obrazovka Slovníček_UJ - ČJ mutace_sekce Práce_Jsem proaktivní čteno jako "Jsem praktivní"

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#41]
**Describe the bug**
[Obrazovka Slovníček_UJ - ČJ mutace_sekce Práce_Jsem proaktivní čteno jako "Jsem pr**a**ktivní"]

**To Reproduce**
[Slovníček - Práce - Jsem proaktivní]

**Expected behavior**
[výraz Jsem proaktivní se po kliknutí na tlačítko zvuku přehraje jako "Jsem proaktivní"]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.7.0
