### ISSUE TITLE
Obrazovka Slovníček_UJ - ČJ mutace_sekce Ve školce - Potřebuješ čůrat? čteno jako "Potřebuješ čéůrat?"

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#42]
**Describe the bug**
[Obrazovka Slovníček_UJ - ČJ mutace_sekce Ve školce - Potřebuješ čůrat? čteno jako "Potřebuješ č**éů**rat?"]

**To Reproduce**
[Slovníček - Ve školce - Potřebuješ čůrat?]

**Expected behavior**
[výraz Potřebuješ čůrat? se po kliknutí na tlačítko zvuku přehraje jako "Potřebuješ čůrat?"]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi 1.7.0
