### ISSUE TITLE
Obrazovka Slovníček_UJ - ČJ mutace_sekce Duševní zdraví_pochopení/porozumění čteno s lomítkem

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#43]
**Describe the bug**
[Obrazovka Slovníček_UJ - ČJ mutace_sekce Duševní zdraví_pochopení/porozumění čteno jako "pochopení lomítko porozumění"]

**To Reproduce**
[Slovníček - Duševní zdraví - pochopení/porozumění]

**Expected behavior**
[výraz pochopení/porozumění se po kliknutí na tlačítko zvuku přehraje jako "pochopení, porozumění"]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.6.1
