### ISSUE TITLE
Obrazovka Slovníček_UJ - ČJ mutace_sekce Duševní zdraví_dát radu/poradit čteno s lomítkem

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#44]
**Describe the bug**
[Obrazovka Slovníček_UJ - ČJ mutace_sekce Duševní zdraví_dát radu/poradit čteno jako "dát radu lomítko poradit"]

**To Reproduce**
[Slovníček - Duševní zdraví - dát radu/poradit]

**Expected behavior**
[výraz dát radu/poradit se po kliknutí na tlačítko zvuku přehraje jako "dát radu, poradit"]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.7.0
