### ISSUE TITLE
Obrazovka Slovníček_UJ - ČJ mutace_sekce Pro děti_puzzle se přehrává jako "pazl"

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#45]
**Describe the bug**
[Obrazovka Slovníček_UJ - ČJ mutace_sekce Pro děti_puzzle se přehrává jako "pazl"]

**To Reproduce**
[Slovníček - Pro děti - puzzle]

**Expected behavior**
[slovo puzzle se po kliknutí na tlačítko zvuku přehraje jako "pucle"]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.6.1

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.7.0
