### ISSUE TITLE
Obrazovka Abeceda_slovenská abeceda_C_výslovnost slova "cop" se přehrává jako "kop"

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#47]
**Describe the bug**
[Obrazovka Abeceda_slovenská abeceda_C_výslovnost slova "cop" se přehrává jako "kop"]

**To Reproduce**
[Abeceda - slovenská abeceda - C]

**Expected behavior**
[slovo cop u písmena C se po kliknutí na tlačítko zvuku přehraje jako "cop"]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.7.0
