### ISSUE TITLE
Obrazovka Slovníček_UJ - ČJ mutace_sekce Práce_výrazy se zkratkou OSVČ jsou čteny jako "osevéčé"

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#48]
**Describe the bug**
[Obrazovka Slovníček_UJ - ČJ mutace_sekce Práce_výrazy "pracovat jako OSVČ" a "osoba samostatně výdělečně činná (OSVČ)" jsou čteny jako "pracovat jako osevéčé" a "osoba samostatně výdělečně činná osevéčé"]

**To Reproduce**
[Slovníček - Práce - pracovat jako OSVČ, osoba samostatně výdělečně činná osevéčé]

**Expected behavior**
[zkratka OSVČ je čtena jako "osvč"?]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.7.0
