### ISSUE TITLE
Obrazovka Slovníček_UJ - ČJ mutace_sekce Duševní zdraví_Kdy se cítíš štastný? Kdy se cítíš šťastná? čteno bez ť

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#49]
**Describe the bug**
[Obrazovka Slovníček_UJ - ČJ mutace_sekce Duševní zdraví_Kdy se cítíš š**t**astný? Kdy se cítíš šťastná? čteno bez ť - v textu i ve výslovnosti chybí háček u t]

**To Reproduce**
[Slovníček - Duševní zdraví - Kdy se cítíš štastný? Kdy se cítíš šťastná?]

**Expected behavior**
[výraz Kdy se cítíš štastný? Kdy se cítíš šťastná? se po kliknutí na tlačítko zvuku přehraje jako "Kdy se cítíš šťastný? Kdy se cítíš šťastná?"]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.7.0
