### ISSUE TITLE
Obrazovka Slovníček_UJ - ČJ mutace_sekce Časopis Raketa dětem_Najdi 10 rozdílů. čteno Najdi deseti rozdílů

### ISSUE THREAD

**Issue by Lebedito** [cesko-digital/movapp-android#50]
**Describe the bug**
[Obrazovka Slovníček_UJ - ČJ mutace_sekce Časopis Raketa dětem_Najdi 10 rozdílů. čteno Najdi deset**i** rozdílů]

**To Reproduce**
[Slovníček - Časopis Raketa dětem - Najdi 10 rozdílů.]

**Expected behavior**
[výraz Najdi 10 rozdílů. se po kliknutí na tlačítko zvuku přehraje jako "Najdi deset rozdílů."]

**Version/Build number**
[See the settings of the app and leave us the build number (if possible).]

**Attachments**
[Optionally, attach screenshots, log files, or error messages ...]

**Comment by matuyka** [comment]
Opraveno ve verzi číslo 1.7.0
